### ISSUE TITLE
Track - Artist - Album Linebreak?

### ISSUE THREAD

**Issue by uberstar100** [kuba160/ddb_discord_presence#10]
I don't really get the foobar2000 formatting enough to apply it to this plugin. I'd like to have the name of the track, artist and album appear on my profile line-by-line like this:

![db](https://i.imgur.com/CLsejME.png)

sorry for the shoddy recreation

**Comment by kuba160** [comment]
I don't think having 3 lines of text is possible.

**Comment by uberstar100** [comment]
> I don't think having 3 lines of text is possible.

oh well, ty though.
