### ISSUE TITLE
Showing cover art from last.fm does not seem to work.

### ISSUE THREAD

**Issue by y9su** [kuba160/ddb_discord_presence#15]
title.

**Comment by kuba160** [comment]
You need to provide more details such as system, plugin and deadbeef version (and where you got it from). Does the plugin work or it is only artwork missing? Is the problem related to song? (do 'lookup on last.fm' on the track and see if the album has artwork for it)
It is working for me: 
![image](https://github.com/kuba160/ddb_discord_presence/assets/6359901/3091073b-0e70-4a6c-a369-c2552a23f4eb)
