### ISSUE TITLE
"deadbeef.h" not found

### ISSUE THREAD

**Issue by Etern1tyDark** [kuba160/ddb_discord_presence#16]
Encountered this issue on https://github.com/Serranya/deadbeef-mpris2-plugin/issues/9, but this plugin doesn't have the equivalent of a configure file, hence i can't make the plugin

```
artwork_internal.c:36:10: fatal error: deadbeef/deadbeef.h: No such file or directory
   36 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

The file exists on /opt/deadbeef/include/deadbeef/

**Comment by Etern1tyDark** [comment]
Ubuntu 22.04, DeaDBeeF installed with deb package.

**Comment by kuba160** [comment]
`discord_presence` plugin expects `deadbeef.h` header file in `/usr/local/include/deadbeef` (or optionally in `deadbeef` plugin source dir). To add lookup extra lookup path you need to run: `make COPT="-I/opt/deadbeef/include"`.
