### ISSUE TITLE
Change "Playing" to "Listening to"

### ISSUE THREAD

**Issue by codefreak558** [kuba160/ddb_discord_presence#18]
Basically the title.

I do know you are able to change the title of what discord's rich presence says. [Example from foobar200 discord presence](https://github.com/TheQwertiest/foo_discord_rich/issues/2)

![image](https://github.com/user-attachments/assets/55a2b730-4fd6-4d74-a235-02fa25a457a1)

**Comment by kuba160** [comment]
If I understand correctly from the link it is not possible without modding Discord, but things might change in the future.
