### ISSUE TITLE
Does this plugin still work

### ISSUE THREAD

**Issue by batmanm0b1E** [kuba160/ddb_discord_presence#3]
Does this plugin still work

**Comment by kuba160** [comment]
Yes, I'm using it every day.

**Comment by batmanm0b1E** [comment]
how do i get it to work? with discord

**Comment by batmanm0b1E** [comment]
I added this file discord_presence.so to/.local/lib/deadbeef/ But how does discord see it? How can i tell if its working

**Comment by kuba160** [comment]
> But how does discord see it?

It is explained in readme, plugin uses discord library that connects to discord client through rpc, nothing to be done on plugin side

> How can i tell if its working

You can check deadbeef settings to see it plugin is installed properly. To check if it's working play some music and check your status on some discord server.

**Comment by batmanm0b1E** [comment]
How do i check my status on discord server to see if its showing up. its in the plugins
http://www.imagebam.com/image/d22a151222142294

**Comment by kuba160** [comment]
You just go on server you would like, and you should be able to see your status on channel's user list
![image](https://user-images.githubusercontent.com/6359901/57735958-99e3c280-76a6-11e9-91d7-e0ed8545f6fa.png)

**Comment by batmanm0b1E** [comment]
Not showing anything for me
![Screenshot_2019-05-14_18-22-14](https://user-images.githubusercontent.com/33992707/57736261-56bd2b80-7675-11e9-9247-8ecf56e85b57.png)

**Comment by batmanm0b1E** [comment]
Do i need discord app installed. i'm using Web version

**Comment by kuba160** [comment]
Yes it's necessary

**Comment by batmanm0b1E** [comment]
i installed discord app and it still doesn't show up next to my name

**Comment by batmanm0b1E** [comment]
OK Now its showing up next to my name COOL fantastic plugin @kuba160 guess it took time

**Comment by okand** [comment]
Bumping an old issue but I'll just add here that the plugin does not work if you installed discord through flatpak. Once I switched to the .deb package it worked immediately.

**Comment by kuba160** [comment]
Well, I would say this is just as intended by the developers, as sandboxing is a feature of flatpak. I just found a document on how to fix this: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
There is also a deadbeef flatpak, which would make things even more complicated.
