### ISSUE TITLE
Metadata not updating

### ISSUE THREAD

**Issue by Sprtcrnbry** [kuba160/ddb_discord_presence#4]
when playing internet radio, the metadata doesn't update on discord: 
![Cuplikan Layar_2019-06-23_13-28-36](https://user-images.githubusercontent.com/17063780/59972576-aae3f580-95bb-11e9-9820-93a92bfab844.png)

**Comment by kuba160** [comment]
you need to enable option in vfs_curl plugin, that emits trackchange if metadata changes

**Comment by Sprtcrnbry** [comment]
on the curl vfs plugin options, there is only one option called "enable logging", is that the right one?

**Comment by kuba160** [comment]
No, there was a different one. I will check it later, not on PC currently.

**Comment by kuba160** [comment]
Commit https://github.com/DeaDBeeF-Player/deadbeef/commit/2d6cf9e8f79d5501a56f0de97bc37e7a24d85f7d#diff-ff5486d33be719eab458440f69ff65e5 removed the option and made the behaviour default, meaning it should work out of box. I'm on vacation now and I will look at the issue when I find time.

**Comment by kuba160** [comment]
I just tested radio I listen to and didn't notice any problems. Tested also with radio you used on screenshot on a blank-new static version of DeaDBeeF 1.8.2 and track change worked just fine.
Also note that discord status updates have a limit of one update per 15 seconds, if internet radio sends some message between songs, then the song title will show up with a delay.

Things you could try are:
1. Upgrade to DeaDBeeF 1.8.2
2. Check if same behavior happens with empty config (your config is probably located in `$HOME/.config/deadbeef`, move it temporarily)
3. Try it with different radio station if same problem persists.
4. (if you're not already using precompiled version from https://deadbeef.sourceforge.net/) Try your luck with static version.

**Comment by Neo-Desktop** [comment]
I just noticed I'm having a similar issue, using DeaDBeeF - 1.8.8

It appears that track change events are not emitted when the streaming metadata for a track is updated

As such, the metadata (or cached metadata) from when playback is initialized is what shows up on Discord 

I can demonstrate this in the following fashion.

The discord track shown is what was being played 25 minutes prior
![image](https://user-images.githubusercontent.com/321592/132265949-e84b95b5-b1ff-44f7-8f6f-b38c9b2bbd0e.png)

Pressing stop, pause, or even play again, will emit a track changed event
![image](https://user-images.githubusercontent.com/321592/132266019-b021fbb4-22b6-426a-8c3c-66f136359b7f.png)

The [DeaDBbeeF GTK Status Notifier Plugin](https://github.com/vovochka404/deadbeef-statusnotifier-plugin), however, does not suffer from these symptoms and correctly triggers a notification status message when the streaming metadata is updated

Looking into their code it appears they issue a tooltip message when a [DDB_PLAYBACK_STATE_PLAYING is emitted](https://github.com/vovochka404/deadbeef-statusnotifier-plugin/blob/master/src/sni_upd.c#L199) and then queries DeaDBeeF for the current track information.

I'm not 100% sure how different their plugin architecture is from this plugin (I haven't messed with DeaDBeeF development yet) but when I have the capacity to take on another project I may tinker around and submit a PR using this updated logic :)

**Comment by kuba160** [comment]
`DB_EV_SONGCHANGED` is indeed not emitted, but this only happens on ogg streams which I didn't test before. AAC and mp3 streams work fine. This is an issue with deadbeef which has been reported. I'll close this issue once a fix has been applied to deadbeef codebase.

**Comment by Neo-Desktop** [comment]
Ah, wow, thank you so much for diving into that - I really appreciate it
I'll follow deadbeef's progress on it, thanks again!

**Comment by kuba160** [comment]
This has been fixed in https://github.com/DeaDBeeF-Player/deadbeef/commit/faa76d83d841e7c247c313cefc173126140b4c82 and https://github.com/DeaDBeeF-Player/deadbeef/commit/2356186b964b1a9056f60e266308ff6e8913fe0e . You can test it by downloading development build or you can wait for next release. There was also an issue with aac streams that was found because of this bug. Thanks for reporting. 🙂
