### ISSUE TITLE
How do I use this Plugin?

### ISSUE THREAD

**Issue by jwddog** [kuba160/ddb_discord_presence#9]
I have downloaded this plugin and added it to my ~/.local/lib/deadbeef/ directory, the plugin is also recognized by deadbeef in the plugins tab. My discord status is not being updated when I am playing music through deadbeef.

How do I get it to change my discord status when I am listening on deadbeef?

**Comment by kuba160** [comment]
Are you using discord installed through flatpak? If yes, see here: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by jwddog** [comment]
I was, thank you so much! I reinstalled it through the pop! shop and it is working just fine now.

**Comment by Neo-Desktop** [comment]
Just wanted to mention that I also fell into this trap with a flatpack version of Discord
Perhaps it may be a good idea to add a troubleshooting section in the description of the plugin or something similar

**Comment by kuba160** [comment]
I was thinking the same, but I was on vacation and didn't want to bother with it. Thanks for reminding me, updated now.
